/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_progra2_eduardoguevara;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edujg
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ap.setArchivo(new File("./planetas.abc"));
        aa.setArchivo(new File("./astro.abc"));
        ap.cargar();
        planetas = ap.getListaa();
        aa.cargar();
        astro = aa.getListaa();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_planeta.getModel();
        for (Planetas p : planetas) {
            modelo.addElement(p);
        }
        cb_planeta.setModel(modelo);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_crew.getModel();
        for (Astronautas a : astro) {
            model.addElement(a);
        }
        cb_crew.setModel(model);
        Object newrow[] = {
            planetas.get(planetas.size() - 1).getNombre(),
            planetas.get(planetas.size() - 1).getTemp(),
            planetas.get(planetas.size() - 1).isAnillos(),
            planetas.get(planetas.size() - 1).getSuperficie(),
            planetas.get(planetas.size() - 1).getDist()
        };
        DefaultTableModel m = (DefaultTableModel) jt_pla.getModel();
        m.addRow(newrow);
        jt_pla.setModel(m);
        Object newro[] = {
            astro.get(astro.size() - 1).getNombre(),
            astro.get(astro.size() - 1).getNacionalidad(),
            astro.get(astro.size() - 1).getSueldo(),
            astro.get(astro.size() - 1).getExperiencia(),
            astro.get(astro.size() - 1).getSexo(),
            astro.get(astro.size() - 1).getPeso()
        };
        DefaultTableModel a = (DefaultTableModel) jt_astro.getModel();
        a.addRow(newro);
        jt_astro.setModel(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_nombrep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        js_temp = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jcbox_anillos = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        tf_superficie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        js_dist = new javax.swing.JSpinner();
        bt_crearpla = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombrea = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_nacio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        js_sueldo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        tf_exp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_sexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        js_peso = new javax.swing.JSpinner();
        bt_creara = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tf_num = new javax.swing.JTextField();
        cb_planeta = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        js_velocidad = new javax.swing.JSpinner();
        bt_crearn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_astro = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_pla = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        cb_nave = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        bt_empezar = new javax.swing.JButton();
        cb_crew = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Temperatura (F):");

        js_temp.setModel(new javax.swing.SpinnerNumberModel());

        jLabel3.setText("Tiene Anillos:");

        jcbox_anillos.setText("Si");

        jLabel4.setText("Tipo de superficie:");

        jLabel5.setText("Distancia de la Tierra:");

        js_dist.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));

        bt_crearpla.setText("Crear");
        bt_crearpla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearplaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jcbox_anillos)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(js_dist))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(js_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(149, 149, 149)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(bt_crearpla)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(js_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_superficie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbox_anillos)
                    .addComponent(jLabel5)
                    .addComponent(js_dist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(bt_crearpla)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Crear Planetas", jPanel1);

        jLabel6.setText(" nombre, nacionalidad, sueldo, experiencia, sexo y peso. ");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Nacionalidad:");

        jLabel9.setText("Sueldo:");

        js_sueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));

        jLabel10.setText("Experiencia:");

        jLabel11.setText("Sexo:");

        jLabel12.setText("Peso:");

        js_peso.setModel(new javax.swing.SpinnerNumberModel());

        bt_creara.setText("Crear");
        bt_creara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nombrea, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(38, 38, 38)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nacio)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(js_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tf_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(js_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_creara)
                        .addComponent(jLabel6)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_nombrea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(tf_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nacio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(js_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(js_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(bt_creara)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Crear Astronautas", jPanel2);

        jLabel13.setText("Numero de Serie:");

        jLabel14.setText("Planeta de destino:");

        jLabel15.setText("Velocidad:");

        bt_crearn.setText("Crear");
        bt_crearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(js_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_num, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(cb_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(bt_crearn)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_num, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(js_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(bt_crearn)
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Crear Nave", jPanel4);

        jt_astro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "Experiencia", "Sexo", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_astro);

        jLabel16.setText("Astronautas:");

        jLabel17.setText("Planetas");

        jt_pla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura (F)", "Tiene anillos", "Superficie", "Distancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_pla);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver", jPanel5);

        jLabel19.setText("Nave:");

        bt_empezar.setText("Empezar");
        bt_empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_empezarMouseClicked(evt);
            }
        });

        jLabel18.setText("Agregar tripulante:");

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(bt_empezar)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_crew, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_nave, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(267, 267, 267))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel19)
                .addGap(29, 29, 29)
                .addComponent(cb_nave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(cb_crew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(bt_empezar)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("Expedicion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearplaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearplaMouseClicked
        // TODO add your handling code here:
        planetas.add(new Planetas(tf_nombrep.getText(), (Integer) js_temp.getValue(), jcbox_anillos.isSelected(), tf_superficie.getText(), (Integer) js_dist.getValue()));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_planeta.getModel();
        modelo.removeAllElements();
        for (Planetas p : planetas) {
            modelo.addElement(p);
        }
        cb_planeta.setModel(modelo);
        ap.setListaa(planetas);
        try {
            ap.escribir();
            JOptionPane.showMessageDialog(this, "Cambio Guardado exitosamente");
        } catch (IOException ex) {

        }
        Object newrow[] = {
            planetas.get(planetas.size() - 1).getNombre(),
            planetas.get(planetas.size() - 1).getTemp(),
            planetas.get(planetas.size() - 1).isAnillos(),
            planetas.get(planetas.size() - 1).getSuperficie(),
            planetas.get(planetas.size() - 1).getDist()
        };
        DefaultTableModel m = (DefaultTableModel) jt_pla.getModel();
        m.addRow(newrow);
        jt_pla.setModel(m);
    }//GEN-LAST:event_bt_crearplaMouseClicked

    private void bt_crearaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearaMouseClicked
        // TODO add your handling code here:
        astro.add(new Astronautas(tf_nombrea.getText(), tf_nacio.getText(), (Double) js_sueldo.getValue(), tf_exp.getText(), tf_sexo.getText(), (Integer) js_peso.getValue()));
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_crew.getModel();
        modelo.removeAllElements();
        for (Astronautas a : astro) {
            modelo.addElement(a);
        }
        cb_crew.setModel(modelo);
        aa.setListaa(astro);
        try {
            aa.escribir();
            JOptionPane.showMessageDialog(this, "Cambio Guardado exitosamente");
        } catch (IOException ex) {

        }
        Object newrow[] = {
            astro.get(astro.size() - 1).getNombre(),
            astro.get(astro.size() - 1).getNacionalidad(),
            astro.get(astro.size() - 1).getSueldo(),
            astro.get(astro.size() - 1).getExperiencia(),
            astro.get(astro.size() - 1).getSexo(),
            astro.get(astro.size() - 1).getPeso()
        };
        DefaultTableModel m = (DefaultTableModel) jt_astro.getModel();
        m.addRow(newrow);
        jt_astro.setModel(m);
    }//GEN-LAST:event_bt_crearaMouseClicked

    private void bt_crearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearnMouseClicked
        // TODO add your handling code here:
        if (cb_planeta.getSelectedItem() == null) {

        } else {
            String a = JOptionPane.showInputDialog(this, "Ingrese si es sonda(0) o tripulada(1)");
            if (Integer.parseInt(a) == 0) {
                String b = JOptionPane.showInputDialog("Ingrese el material de la nave");
                naves.add(new Sonda(b, (Integer) js_peso.getValue(), Integer.parseInt(tf_num.getText()), (Planetas) cb_planeta.getSelectedItem(), (Integer) js_velocidad.getValue()));
                tf_num.setText("");
                cb_planeta.setSelectedItem(0);
                js_velocidad.setValue(0);
            } else if (Integer.parseInt(a) == 1) {
                String b = JOptionPane.showInputDialog("Ingrese el lugar de destino:");
                naves.add(new Tripulada(b, Integer.parseInt(tf_num.getText()), (Planetas) cb_planeta.getSelectedItem(), (Integer) js_velocidad.getValue()));
                tf_num.setText("");
                cb_planeta.setSelectedItem(0);
                js_velocidad.setValue(0);
            } else {
                JOptionPane.showMessageDialog(this, "Respuesta invalida");
            }
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_nave.getModel();
        modelo.removeAllElements();
        for (Naves n : naves) {
            modelo.addElement(n);
        }
        cb_nave.setModel(modelo);
    }//GEN-LAST:event_bt_crearnMouseClicked

    private void bt_empezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_empezarMouseClicked
        // TODO add your handling code here:
        System.out.println(((Naves) cb_nave.getSelectedItem()).getDestino());
        System.out.println((Naves) cb_nave.getSelectedItem());
        Expedicion ex = new Expedicion(((Naves) cb_nave.getSelectedItem()).getDestino(), (Naves) cb_nave.getSelectedItem());
        ex.start();
        for (Naves n : naves) {
            if (n.equals((Naves) cb_nave.getSelectedItem())) {
                naves.remove(n);
                break;
            }
        }
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_nave.getModel();
        modelo.removeAllElements();
        for (Naves n : naves) {
            modelo.addElement(n);
        }
        cb_nave.setModel(modelo);
    }//GEN-LAST:event_bt_empezarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (cb_nave.getSelectedIndex() != -1 && cb_nave.getSelectedItem() instanceof Tripulada && cb_crew.getSelectedItem() != null) {
            ((Tripulada) cb_nave.getSelectedItem()).getCrew().add((Astronautas) cb_crew.getSelectedItem());
            cb_crew.remove(cb_crew.getSelectedIndex());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_creara;
    private javax.swing.JButton bt_crearn;
    private javax.swing.JButton bt_crearpla;
    private javax.swing.JButton bt_empezar;
    private javax.swing.JComboBox<String> cb_crew;
    private javax.swing.JComboBox<String> cb_nave;
    private javax.swing.JComboBox<String> cb_planeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcbox_anillos;
    private javax.swing.JSpinner js_dist;
    private javax.swing.JSpinner js_peso;
    private javax.swing.JSpinner js_sueldo;
    private javax.swing.JSpinner js_temp;
    private javax.swing.JSpinner js_velocidad;
    private javax.swing.JTable jt_astro;
    private javax.swing.JTable jt_pla;
    private javax.swing.JTextField tf_exp;
    private javax.swing.JTextField tf_nacio;
    private javax.swing.JTextField tf_nombrea;
    private javax.swing.JTextField tf_nombrep;
    private javax.swing.JTextField tf_num;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_superficie;
    // End of variables declaration//GEN-END:variables
    ArrayList<Astronautas> astro = new ArrayList();
    ArrayList<Planetas> planetas = new ArrayList();
    ArrayList<Naves> naves = new ArrayList();
    Planetas actual;
    Naves act;
    adminPlanetas ap = new adminPlanetas();
    adminAstro aa = new adminAstro();
}
